2020-03-31 12:09:45,434 ERROR: Exception on /auth/login [GET] [in /home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./edmondsonline/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/khammrich/edmondsonline/edmondsonline/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/khammrich/edmondsonline/edmondsonline/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "html"
    {% block body -%}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 29, in block "body"
    {% block scripts %}
  File "/home/khammrich/edmondsonline/edmondsonline/templates/base.html", line 53, in block "scripts"
    {{ super() }}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 31, in block "scripts"
    <script src="{{bootstrap_find_resource('umd/popper.js', cdn='popper')}}"></script>
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/__init__.py", line 115, in bootstrap_find_resource
    resource_url = cdns[cdn].get_resource_url(filename)
KeyError: 'popper'
2020-03-31 12:26:39,619 ERROR: Exception on /robots.txt [GET] [in /home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "./edmondsonline/errors/handlers.py", line 8, in not_found_error
    return render_template('errors/404.html'), 404
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/khammrich/edmondsonline/edmondsonline/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/khammrich/edmondsonline/edmondsonline/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "html"
    {% block body -%}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 29, in block "body"
    {% block scripts %}
  File "/home/khammrich/edmondsonline/edmondsonline/templates/base.html", line 53, in block "scripts"
    {{ super() }}
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 31, in block "scripts"
    <script src="{{bootstrap_find_resource('umd/popper.js', cdn='popper')}}"></script>
  File "/home/khammrich/edmondsonline/env/lib/python3.6/site-packages/flask_bootstrap/__init__.py", line 115, in bootstrap_find_resource
    resource_url = cdns[cdn].get_resource_url(filename)
KeyError: 'popper'
