2020-04-02 17:05:15,298 ERROR: Exception on /auth/login [GET] [in /home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./edmondsonline/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/khammrich/test-edmondsonline/edmondsonline/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/khammrich/test-edmondsonline/edmondsonline/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/khammrich/test-edmondsonline/edmondsonline/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/khammrich/test-edmondsonline/edmondsonline/templates/auth/login.html", line 12, in block "app_content"
    {% include 'login_banner.html' %}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login_banner.html
2020-04-02 17:06:18,754 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:06:19,462 ERROR: Exception on /auth/login [GET] [in /home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./edmondsonline/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/khammrich/test-edmondsonline/edmondsonline/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/khammrich/test-edmondsonline/edmondsonline/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/khammrich/test-edmondsonline/edmondsonline/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/khammrich/test-edmondsonline/edmondsonline/templates/auth/login.html", line 12, in block "app_content"
    {% include 'login_banner.html' %}
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/khammrich/test-edmondsonline/venv-edtest/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login_banner.html
2020-04-02 17:07:00,899 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:08:32,810 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:08:48,690 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:09:22,197 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:09:40,261 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:11:22,704 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:12:09,354 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:13:10,074 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:13:41,986 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:14:06,708 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:15:12,415 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:17:15,117 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:17:49,519 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:18:37,760 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:19:21,814 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
2020-04-02 17:19:41,098 INFO: Microblog startup [in ./edmondsonline/__init__.py:75]
